package com.xd.leplay.store.model.proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

public final class Packet {
  private Packet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqPacketOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string udi = 1;
    /**
     * <code>required string udi = 1;</code>
     *
     * <pre>
     * 设备信息
     * </pre>
     */
    boolean hasUdi();
    /**
     * <code>required string udi = 1;</code>
     *
     * <pre>
     * 设备信息
     * </pre>
     */
    java.lang.String getUdi();
    /**
     * <code>required string udi = 1;</code>
     *
     * <pre>
     * 设备信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getUdiBytes();

    // repeated string action = 2;
    /**
     * <code>repeated string action = 2;</code>
     *
     * <pre>
     * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
     * </pre>
     */
    java.util.List<java.lang.String>
    getActionList();
    /**
     * <code>repeated string action = 2;</code>
     *
     * <pre>
     * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
     * </pre>
     */
    int getActionCount();
    /**
     * <code>repeated string action = 2;</code>
     *
     * <pre>
     * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
     * </pre>
     */
    java.lang.String getAction(int index);
    /**
     * <code>repeated string action = 2;</code>
     *
     * <pre>
     * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
     * </pre>
     */
    com.google.protobuf.ByteString
        getActionBytes(int index);

    // repeated bytes params = 3;
    /**
     * <code>repeated bytes params = 3;</code>
     *
     * <pre>
     * 参数（根据action中定义的操作，上传对应的请求参数）
     * </pre>
     */
    java.util.List<com.google.protobuf.ByteString> getParamsList();
    /**
     * <code>repeated bytes params = 3;</code>
     *
     * <pre>
     * 参数（根据action中定义的操作，上传对应的请求参数）
     * </pre>
     */
    int getParamsCount();
    /**
     * <code>repeated bytes params = 3;</code>
     *
     * <pre>
     * 参数（根据action中定义的操作，上传对应的请求参数）
     * </pre>
     */
    com.google.protobuf.ByteString getParams(int index);

    // optional string clientVer = 4;
    /**
     * <code>optional string clientVer = 4;</code>
     *
     * <pre>
     * 应用的版本
     * </pre>
     */
    boolean hasClientVer();
    /**
     * <code>optional string clientVer = 4;</code>
     *
     * <pre>
     * 应用的版本
     * </pre>
     */
    java.lang.String getClientVer();
    /**
     * <code>optional string clientVer = 4;</code>
     *
     * <pre>
     * 应用的版本
     * </pre>
     */
    com.google.protobuf.ByteString
        getClientVerBytes();

    // optional string channel = 5;
    /**
     * <code>optional string channel = 5;</code>
     *
     * <pre>
     * 注册的渠道号
     * </pre>
     */
    boolean hasChannel();
    /**
     * <code>optional string channel = 5;</code>
     *
     * <pre>
     * 注册的渠道号
     * </pre>
     */
    java.lang.String getChannel();
    /**
     * <code>optional string channel = 5;</code>
     *
     * <pre>
     * 注册的渠道号
     * </pre>
     */
    com.google.protobuf.ByteString
        getChannelBytes();
  }
  /**
   * Protobuf type {@code ReqPacket}
   *
   * <pre>
   *============================================ 请求包与响应包
   * </pre>
   */
  public static final class ReqPacket extends
      com.google.protobuf.GeneratedMessage
      implements ReqPacketOrBuilder {
    // Use ReqPacket.newBuilder() to construct.
    private ReqPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqPacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqPacket defaultInstance;
    public static ReqPacket getDefaultInstance() {
      return defaultInstance;
    }

    public ReqPacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              udi_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                action_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              action_.add(input.readBytes());
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                params_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000004;
              }
              params_.add(input.readBytes());
              break;
            }
            case 34: {
              bitField0_ |= 0x00000002;
              clientVer_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000004;
              channel_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          action_ = new com.google.protobuf.UnmodifiableLazyStringList(action_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          params_ = java.util.Collections.unmodifiableList(params_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Packet.internal_static_ReqPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Packet.internal_static_ReqPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Packet.ReqPacket.class, Packet.ReqPacket.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqPacket> PARSER =
        new com.google.protobuf.AbstractParser<ReqPacket>() {
      public ReqPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqPacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqPacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string udi = 1;
    public static final int UDI_FIELD_NUMBER = 1;
    private java.lang.Object udi_;
    /**
     * <code>required string udi = 1;</code>
     *
     * <pre>
     * 设备信息
     * </pre>
     */
    public boolean hasUdi() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string udi = 1;</code>
     *
     * <pre>
     * 设备信息
     * </pre>
     */
    public java.lang.String getUdi() {
      java.lang.Object ref = udi_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          udi_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string udi = 1;</code>
     *
     * <pre>
     * 设备信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUdiBytes() {
      java.lang.Object ref = udi_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        udi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string action = 2;
    public static final int ACTION_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList action_;
    /**
     * <code>repeated string action = 2;</code>
     *
     * <pre>
     * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
     * </pre>
     */
    public java.util.List<java.lang.String>
        getActionList() {
      return action_;
    }
    /**
     * <code>repeated string action = 2;</code>
     *
     * <pre>
     * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
     * </pre>
     */
    public int getActionCount() {
      return action_.size();
    }
    /**
     * <code>repeated string action = 2;</code>
     *
     * <pre>
     * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
     * </pre>
     */
    public java.lang.String getAction(int index) {
      return action_.get(index);
    }
    /**
     * <code>repeated string action = 2;</code>
     *
     * <pre>
     * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
     * </pre>
     */
    public com.google.protobuf.ByteString
        getActionBytes(int index) {
      return action_.getByteString(index);
    }

    // repeated bytes params = 3;
    public static final int PARAMS_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> params_;
    /**
     * <code>repeated bytes params = 3;</code>
     *
     * <pre>
     * 参数（根据action中定义的操作，上传对应的请求参数）
     * </pre>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getParamsList() {
      return params_;
    }
    /**
     * <code>repeated bytes params = 3;</code>
     *
     * <pre>
     * 参数（根据action中定义的操作，上传对应的请求参数）
     * </pre>
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <code>repeated bytes params = 3;</code>
     *
     * <pre>
     * 参数（根据action中定义的操作，上传对应的请求参数）
     * </pre>
     */
    public com.google.protobuf.ByteString getParams(int index) {
      return params_.get(index);
    }

    // optional string clientVer = 4;
    public static final int CLIENTVER_FIELD_NUMBER = 4;
    private java.lang.Object clientVer_;
    /**
     * <code>optional string clientVer = 4;</code>
     *
     * <pre>
     * 应用的版本
     * </pre>
     */
    public boolean hasClientVer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string clientVer = 4;</code>
     *
     * <pre>
     * 应用的版本
     * </pre>
     */
    public java.lang.String getClientVer() {
      java.lang.Object ref = clientVer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientVer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clientVer = 4;</code>
     *
     * <pre>
     * 应用的版本
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClientVerBytes() {
      java.lang.Object ref = clientVer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientVer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string channel = 5;
    public static final int CHANNEL_FIELD_NUMBER = 5;
    private java.lang.Object channel_;
    /**
     * <code>optional string channel = 5;</code>
     *
     * <pre>
     * 注册的渠道号
     * </pre>
     */
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string channel = 5;</code>
     *
     * <pre>
     * 注册的渠道号
     * </pre>
     */
    public java.lang.String getChannel() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          channel_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string channel = 5;</code>
     *
     * <pre>
     * 注册的渠道号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getChannelBytes() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      udi_ = "";
      action_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      params_ = java.util.Collections.emptyList();
      clientVer_ = "";
      channel_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUdi()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUdiBytes());
      }
      for (int i = 0; i < action_.size(); i++) {
        output.writeBytes(2, action_.getByteString(i));
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeBytes(3, params_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(4, getClientVerBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(5, getChannelBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUdiBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < action_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(action_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getActionList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < params_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(params_.get(i));
        }
        size += dataSize;
        size += 1 * getParamsList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getClientVerBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getChannelBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Packet.ReqPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Packet.ReqPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Packet.ReqPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Packet.ReqPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Packet.ReqPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Packet.ReqPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Packet.ReqPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Packet.ReqPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Packet.ReqPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Packet.ReqPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Packet.ReqPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReqPacket}
     *
     * <pre>
     *============================================ 请求包与响应包
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Packet.ReqPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Packet.internal_static_ReqPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Packet.internal_static_ReqPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Packet.ReqPacket.class, Packet.ReqPacket.Builder.class);
      }

      // Construct using Packet.ReqPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        udi_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        params_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        clientVer_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        channel_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Packet.internal_static_ReqPacket_descriptor;
      }

      public Packet.ReqPacket getDefaultInstanceForType() {
        return Packet.ReqPacket.getDefaultInstance();
      }

      public Packet.ReqPacket build() {
        Packet.ReqPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Packet.ReqPacket buildPartial() {
        Packet.ReqPacket result = new Packet.ReqPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.udi_ = udi_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          action_ = new com.google.protobuf.UnmodifiableLazyStringList(
              action_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.action_ = action_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          params_ = java.util.Collections.unmodifiableList(params_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.params_ = params_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientVer_ = clientVer_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000004;
        }
        result.channel_ = channel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Packet.ReqPacket) {
          return mergeFrom((Packet.ReqPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Packet.ReqPacket other) {
        if (other == Packet.ReqPacket.getDefaultInstance()) return this;
        if (other.hasUdi()) {
          bitField0_ |= 0x00000001;
          udi_ = other.udi_;
          onChanged();
        }
        if (!other.action_.isEmpty()) {
          if (action_.isEmpty()) {
            action_ = other.action_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureActionIsMutable();
            action_.addAll(other.action_);
          }
          onChanged();
        }
        if (!other.params_.isEmpty()) {
          if (params_.isEmpty()) {
            params_ = other.params_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureParamsIsMutable();
            params_.addAll(other.params_);
          }
          onChanged();
        }
        if (other.hasClientVer()) {
          bitField0_ |= 0x00000008;
          clientVer_ = other.clientVer_;
          onChanged();
        }
        if (other.hasChannel()) {
          bitField0_ |= 0x00000010;
          channel_ = other.channel_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUdi()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Packet.ReqPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Packet.ReqPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string udi = 1;
      private java.lang.Object udi_ = "";
      /**
       * <code>required string udi = 1;</code>
       *
       * <pre>
       * 设备信息
       * </pre>
       */
      public boolean hasUdi() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string udi = 1;</code>
       *
       * <pre>
       * 设备信息
       * </pre>
       */
      public java.lang.String getUdi() {
        java.lang.Object ref = udi_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          udi_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string udi = 1;</code>
       *
       * <pre>
       * 设备信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUdiBytes() {
        java.lang.Object ref = udi_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          udi_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string udi = 1;</code>
       *
       * <pre>
       * 设备信息
       * </pre>
       */
      public Builder setUdi(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        udi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string udi = 1;</code>
       *
       * <pre>
       * 设备信息
       * </pre>
       */
      public Builder clearUdi() {
        bitField0_ = (bitField0_ & ~0x00000001);
        udi_ = getDefaultInstance().getUdi();
        onChanged();
        return this;
      }
      /**
       * <code>required string udi = 1;</code>
       *
       * <pre>
       * 设备信息
       * </pre>
       */
      public Builder setUdiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        udi_ = value;
        onChanged();
        return this;
      }

      // repeated string action = 2;
      private com.google.protobuf.LazyStringList action_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureActionIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          action_ = new com.google.protobuf.LazyStringArrayList(action_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string action = 2;</code>
       *
       * <pre>
       * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
       * </pre>
       */
      public java.util.List<java.lang.String>
          getActionList() {
        return java.util.Collections.unmodifiableList(action_);
      }
      /**
       * <code>repeated string action = 2;</code>
       *
       * <pre>
       * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
       * </pre>
       */
      public int getActionCount() {
        return action_.size();
      }
      /**
       * <code>repeated string action = 2;</code>
       *
       * <pre>
       * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
       * </pre>
       */
      public java.lang.String getAction(int index) {
        return action_.get(index);
      }
      /**
       * <code>repeated string action = 2;</code>
       *
       * <pre>
       * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
       * </pre>
       */
      public com.google.protobuf.ByteString
          getActionBytes(int index) {
        return action_.getByteString(index);
      }
      /**
       * <code>repeated string action = 2;</code>
       *
       * <pre>
       * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
       * </pre>
       */
      public Builder setAction(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureActionIsMutable();
        action_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string action = 2;</code>
       *
       * <pre>
       * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
       * </pre>
       */
      public Builder addAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureActionIsMutable();
        action_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string action = 2;</code>
       *
       * <pre>
       * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
       * </pre>
       */
      public Builder addAllAction(
          java.lang.Iterable<java.lang.String> values) {
        ensureActionIsMutable();
        super.addAll(values, action_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string action = 2;</code>
       *
       * <pre>
       * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
       * </pre>
       */
      public Builder clearAction() {
        action_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string action = 2;</code>
       *
       * <pre>
       * 操作（协议更新，在协议名后加版本号，如：RegUser_V2）
       * </pre>
       */
      public Builder addActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureActionIsMutable();
        action_.add(value);
        onChanged();
        return this;
      }

      // repeated bytes params = 3;
      private java.util.List<com.google.protobuf.ByteString> params_ = java.util.Collections.emptyList();
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          params_ = new java.util.ArrayList<com.google.protobuf.ByteString>(params_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated bytes params = 3;</code>
       *
       * <pre>
       * 参数（根据action中定义的操作，上传对应的请求参数）
       * </pre>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getParamsList() {
        return java.util.Collections.unmodifiableList(params_);
      }
      /**
       * <code>repeated bytes params = 3;</code>
       *
       * <pre>
       * 参数（根据action中定义的操作，上传对应的请求参数）
       * </pre>
       */
      public int getParamsCount() {
        return params_.size();
      }
      /**
       * <code>repeated bytes params = 3;</code>
       *
       * <pre>
       * 参数（根据action中定义的操作，上传对应的请求参数）
       * </pre>
       */
      public com.google.protobuf.ByteString getParams(int index) {
        return params_.get(index);
      }
      /**
       * <code>repeated bytes params = 3;</code>
       *
       * <pre>
       * 参数（根据action中定义的操作，上传对应的请求参数）
       * </pre>
       */
      public Builder setParams(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes params = 3;</code>
       *
       * <pre>
       * 参数（根据action中定义的操作，上传对应的请求参数）
       * </pre>
       */
      public Builder addParams(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes params = 3;</code>
       *
       * <pre>
       * 参数（根据action中定义的操作，上传对应的请求参数）
       * </pre>
       */
      public Builder addAllParams(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureParamsIsMutable();
        super.addAll(values, params_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes params = 3;</code>
       *
       * <pre>
       * 参数（根据action中定义的操作，上传对应的请求参数）
       * </pre>
       */
      public Builder clearParams() {
        params_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // optional string clientVer = 4;
      private java.lang.Object clientVer_ = "";
      /**
       * <code>optional string clientVer = 4;</code>
       *
       * <pre>
       * 应用的版本
       * </pre>
       */
      public boolean hasClientVer() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string clientVer = 4;</code>
       *
       * <pre>
       * 应用的版本
       * </pre>
       */
      public java.lang.String getClientVer() {
        java.lang.Object ref = clientVer_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clientVer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientVer = 4;</code>
       *
       * <pre>
       * 应用的版本
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClientVerBytes() {
        java.lang.Object ref = clientVer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientVer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientVer = 4;</code>
       *
       * <pre>
       * 应用的版本
       * </pre>
       */
      public Builder setClientVer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        clientVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientVer = 4;</code>
       *
       * <pre>
       * 应用的版本
       * </pre>
       */
      public Builder clearClientVer() {
        bitField0_ = (bitField0_ & ~0x00000008);
        clientVer_ = getDefaultInstance().getClientVer();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientVer = 4;</code>
       *
       * <pre>
       * 应用的版本
       * </pre>
       */
      public Builder setClientVerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        clientVer_ = value;
        onChanged();
        return this;
      }

      // optional string channel = 5;
      private java.lang.Object channel_ = "";
      /**
       * <code>optional string channel = 5;</code>
       *
       * <pre>
       * 注册的渠道号
       * </pre>
       */
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string channel = 5;</code>
       *
       * <pre>
       * 注册的渠道号
       * </pre>
       */
      public java.lang.String getChannel() {
        java.lang.Object ref = channel_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          channel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string channel = 5;</code>
       *
       * <pre>
       * 注册的渠道号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getChannelBytes() {
        java.lang.Object ref = channel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string channel = 5;</code>
       *
       * <pre>
       * 注册的渠道号
       * </pre>
       */
      public Builder setChannel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string channel = 5;</code>
       *
       * <pre>
       * 注册的渠道号
       * </pre>
       */
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        channel_ = getDefaultInstance().getChannel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string channel = 5;</code>
       *
       * <pre>
       * 注册的渠道号
       * </pre>
       */
      public Builder setChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        channel_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReqPacket)
    }

    static {
      defaultInstance = new ReqPacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ReqPacket)
  }

  public interface RspPacketOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 rescode = 1;
    /**
     * <code>required int32 rescode = 1;</code>
     *
     * <pre>
     * 响应码（
     * </pre>
     */
    boolean hasRescode();
    /**
     * <code>required int32 rescode = 1;</code>
     *
     * <pre>
     * 响应码（
     * </pre>
     */
    int getRescode();

    // required string resmsg = 2;
    /**
     * <code>required string resmsg = 2;</code>
     *
     * <pre>
     * 响应消息
     * </pre>
     */
    boolean hasResmsg();
    /**
     * <code>required string resmsg = 2;</code>
     *
     * <pre>
     * 响应消息
     * </pre>
     */
    java.lang.String getResmsg();
    /**
     * <code>required string resmsg = 2;</code>
     *
     * <pre>
     * 响应消息
     * </pre>
     */
    com.google.protobuf.ByteString
        getResmsgBytes();

    // repeated string action = 3;
    /**
     * <code>repeated string action = 3;</code>
     *
     * <pre>
     * 响应操作
     * </pre>
     */
    java.util.List<java.lang.String>
    getActionList();
    /**
     * <code>repeated string action = 3;</code>
     *
     * <pre>
     * 响应操作
     * </pre>
     */
    int getActionCount();
    /**
     * <code>repeated string action = 3;</code>
     *
     * <pre>
     * 响应操作
     * </pre>
     */
    java.lang.String getAction(int index);
    /**
     * <code>repeated string action = 3;</code>
     *
     * <pre>
     * 响应操作
     * </pre>
     */
    com.google.protobuf.ByteString
        getActionBytes(int index);

    // repeated bytes params = 4;
    /**
     * <code>repeated bytes params = 4;</code>
     *
     * <pre>
     * 响应参数
     * </pre>
     */
    java.util.List<com.google.protobuf.ByteString> getParamsList();
    /**
     * <code>repeated bytes params = 4;</code>
     *
     * <pre>
     * 响应参数
     * </pre>
     */
    int getParamsCount();
    /**
     * <code>repeated bytes params = 4;</code>
     *
     * <pre>
     * 响应参数
     * </pre>
     */
    com.google.protobuf.ByteString getParams(int index);
  }
  /**
   * Protobuf type {@code RspPacket}
   */
  public static final class RspPacket extends
      com.google.protobuf.GeneratedMessage
      implements RspPacketOrBuilder {
    // Use RspPacket.newBuilder() to construct.
    private RspPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RspPacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RspPacket defaultInstance;
    public static RspPacket getDefaultInstance() {
      return defaultInstance;
    }

    public RspPacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RspPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rescode_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              resmsg_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                action_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              action_.add(input.readBytes());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                params_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000008;
              }
              params_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          action_ = new com.google.protobuf.UnmodifiableLazyStringList(action_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          params_ = java.util.Collections.unmodifiableList(params_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Packet.internal_static_RspPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Packet.internal_static_RspPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Packet.RspPacket.class, Packet.RspPacket.Builder.class);
    }

    public static com.google.protobuf.Parser<RspPacket> PARSER =
        new com.google.protobuf.AbstractParser<RspPacket>() {
      public RspPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RspPacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RspPacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 rescode = 1;
    public static final int RESCODE_FIELD_NUMBER = 1;
    private int rescode_;
    /**
     * <code>required int32 rescode = 1;</code>
     *
     * <pre>
     * 响应码（
     * </pre>
     */
    public boolean hasRescode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 rescode = 1;</code>
     *
     * <pre>
     * 响应码（
     * </pre>
     */
    public int getRescode() {
      return rescode_;
    }

    // required string resmsg = 2;
    public static final int RESMSG_FIELD_NUMBER = 2;
    private java.lang.Object resmsg_;
    /**
     * <code>required string resmsg = 2;</code>
     *
     * <pre>
     * 响应消息
     * </pre>
     */
    public boolean hasResmsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string resmsg = 2;</code>
     *
     * <pre>
     * 响应消息
     * </pre>
     */
    public java.lang.String getResmsg() {
      java.lang.Object ref = resmsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resmsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string resmsg = 2;</code>
     *
     * <pre>
     * 响应消息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getResmsgBytes() {
      java.lang.Object ref = resmsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resmsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string action = 3;
    public static final int ACTION_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList action_;
    /**
     * <code>repeated string action = 3;</code>
     *
     * <pre>
     * 响应操作
     * </pre>
     */
    public java.util.List<java.lang.String>
        getActionList() {
      return action_;
    }
    /**
     * <code>repeated string action = 3;</code>
     *
     * <pre>
     * 响应操作
     * </pre>
     */
    public int getActionCount() {
      return action_.size();
    }
    /**
     * <code>repeated string action = 3;</code>
     *
     * <pre>
     * 响应操作
     * </pre>
     */
    public java.lang.String getAction(int index) {
      return action_.get(index);
    }
    /**
     * <code>repeated string action = 3;</code>
     *
     * <pre>
     * 响应操作
     * </pre>
     */
    public com.google.protobuf.ByteString
        getActionBytes(int index) {
      return action_.getByteString(index);
    }

    // repeated bytes params = 4;
    public static final int PARAMS_FIELD_NUMBER = 4;
    private java.util.List<com.google.protobuf.ByteString> params_;
    /**
     * <code>repeated bytes params = 4;</code>
     *
     * <pre>
     * 响应参数
     * </pre>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getParamsList() {
      return params_;
    }
    /**
     * <code>repeated bytes params = 4;</code>
     *
     * <pre>
     * 响应参数
     * </pre>
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <code>repeated bytes params = 4;</code>
     *
     * <pre>
     * 响应参数
     * </pre>
     */
    public com.google.protobuf.ByteString getParams(int index) {
      return params_.get(index);
    }

    private void initFields() {
      rescode_ = 0;
      resmsg_ = "";
      action_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      params_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRescode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResmsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, rescode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getResmsgBytes());
      }
      for (int i = 0; i < action_.size(); i++) {
        output.writeBytes(3, action_.getByteString(i));
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeBytes(4, params_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rescode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getResmsgBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < action_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(action_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getActionList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < params_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(params_.get(i));
        }
        size += dataSize;
        size += 1 * getParamsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Packet.RspPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Packet.RspPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Packet.RspPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Packet.RspPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Packet.RspPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Packet.RspPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Packet.RspPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Packet.RspPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Packet.RspPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Packet.RspPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Packet.RspPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RspPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Packet.RspPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Packet.internal_static_RspPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Packet.internal_static_RspPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Packet.RspPacket.class, Packet.RspPacket.Builder.class);
      }

      // Construct using Packet.RspPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rescode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        resmsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        action_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        params_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Packet.internal_static_RspPacket_descriptor;
      }

      public Packet.RspPacket getDefaultInstanceForType() {
        return Packet.RspPacket.getDefaultInstance();
      }

      public Packet.RspPacket build() {
        Packet.RspPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Packet.RspPacket buildPartial() {
        Packet.RspPacket result = new Packet.RspPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rescode_ = rescode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.resmsg_ = resmsg_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          action_ = new com.google.protobuf.UnmodifiableLazyStringList(
              action_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.action_ = action_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          params_ = java.util.Collections.unmodifiableList(params_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.params_ = params_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Packet.RspPacket) {
          return mergeFrom((Packet.RspPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Packet.RspPacket other) {
        if (other == Packet.RspPacket.getDefaultInstance()) return this;
        if (other.hasRescode()) {
          setRescode(other.getRescode());
        }
        if (other.hasResmsg()) {
          bitField0_ |= 0x00000002;
          resmsg_ = other.resmsg_;
          onChanged();
        }
        if (!other.action_.isEmpty()) {
          if (action_.isEmpty()) {
            action_ = other.action_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureActionIsMutable();
            action_.addAll(other.action_);
          }
          onChanged();
        }
        if (!other.params_.isEmpty()) {
          if (params_.isEmpty()) {
            params_ = other.params_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureParamsIsMutable();
            params_.addAll(other.params_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRescode()) {
          
          return false;
        }
        if (!hasResmsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Packet.RspPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Packet.RspPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 rescode = 1;
      private int rescode_ ;
      /**
       * <code>required int32 rescode = 1;</code>
       *
       * <pre>
       * 响应码（
       * </pre>
       */
      public boolean hasRescode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 rescode = 1;</code>
       *
       * <pre>
       * 响应码（
       * </pre>
       */
      public int getRescode() {
        return rescode_;
      }
      /**
       * <code>required int32 rescode = 1;</code>
       *
       * <pre>
       * 响应码（
       * </pre>
       */
      public Builder setRescode(int value) {
        bitField0_ |= 0x00000001;
        rescode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rescode = 1;</code>
       *
       * <pre>
       * 响应码（
       * </pre>
       */
      public Builder clearRescode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rescode_ = 0;
        onChanged();
        return this;
      }

      // required string resmsg = 2;
      private java.lang.Object resmsg_ = "";
      /**
       * <code>required string resmsg = 2;</code>
       *
       * <pre>
       * 响应消息
       * </pre>
       */
      public boolean hasResmsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string resmsg = 2;</code>
       *
       * <pre>
       * 响应消息
       * </pre>
       */
      public java.lang.String getResmsg() {
        java.lang.Object ref = resmsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          resmsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string resmsg = 2;</code>
       *
       * <pre>
       * 响应消息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getResmsgBytes() {
        java.lang.Object ref = resmsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resmsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string resmsg = 2;</code>
       *
       * <pre>
       * 响应消息
       * </pre>
       */
      public Builder setResmsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resmsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string resmsg = 2;</code>
       *
       * <pre>
       * 响应消息
       * </pre>
       */
      public Builder clearResmsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resmsg_ = getDefaultInstance().getResmsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string resmsg = 2;</code>
       *
       * <pre>
       * 响应消息
       * </pre>
       */
      public Builder setResmsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resmsg_ = value;
        onChanged();
        return this;
      }

      // repeated string action = 3;
      private com.google.protobuf.LazyStringList action_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureActionIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          action_ = new com.google.protobuf.LazyStringArrayList(action_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string action = 3;</code>
       *
       * <pre>
       * 响应操作
       * </pre>
       */
      public java.util.List<java.lang.String>
          getActionList() {
        return java.util.Collections.unmodifiableList(action_);
      }
      /**
       * <code>repeated string action = 3;</code>
       *
       * <pre>
       * 响应操作
       * </pre>
       */
      public int getActionCount() {
        return action_.size();
      }
      /**
       * <code>repeated string action = 3;</code>
       *
       * <pre>
       * 响应操作
       * </pre>
       */
      public java.lang.String getAction(int index) {
        return action_.get(index);
      }
      /**
       * <code>repeated string action = 3;</code>
       *
       * <pre>
       * 响应操作
       * </pre>
       */
      public com.google.protobuf.ByteString
          getActionBytes(int index) {
        return action_.getByteString(index);
      }
      /**
       * <code>repeated string action = 3;</code>
       *
       * <pre>
       * 响应操作
       * </pre>
       */
      public Builder setAction(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureActionIsMutable();
        action_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string action = 3;</code>
       *
       * <pre>
       * 响应操作
       * </pre>
       */
      public Builder addAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureActionIsMutable();
        action_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string action = 3;</code>
       *
       * <pre>
       * 响应操作
       * </pre>
       */
      public Builder addAllAction(
          java.lang.Iterable<java.lang.String> values) {
        ensureActionIsMutable();
        super.addAll(values, action_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string action = 3;</code>
       *
       * <pre>
       * 响应操作
       * </pre>
       */
      public Builder clearAction() {
        action_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string action = 3;</code>
       *
       * <pre>
       * 响应操作
       * </pre>
       */
      public Builder addActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureActionIsMutable();
        action_.add(value);
        onChanged();
        return this;
      }

      // repeated bytes params = 4;
      private java.util.List<com.google.protobuf.ByteString> params_ = java.util.Collections.emptyList();
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          params_ = new java.util.ArrayList<com.google.protobuf.ByteString>(params_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated bytes params = 4;</code>
       *
       * <pre>
       * 响应参数
       * </pre>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getParamsList() {
        return java.util.Collections.unmodifiableList(params_);
      }
      /**
       * <code>repeated bytes params = 4;</code>
       *
       * <pre>
       * 响应参数
       * </pre>
       */
      public int getParamsCount() {
        return params_.size();
      }
      /**
       * <code>repeated bytes params = 4;</code>
       *
       * <pre>
       * 响应参数
       * </pre>
       */
      public com.google.protobuf.ByteString getParams(int index) {
        return params_.get(index);
      }
      /**
       * <code>repeated bytes params = 4;</code>
       *
       * <pre>
       * 响应参数
       * </pre>
       */
      public Builder setParams(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes params = 4;</code>
       *
       * <pre>
       * 响应参数
       * </pre>
       */
      public Builder addParams(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes params = 4;</code>
       *
       * <pre>
       * 响应参数
       * </pre>
       */
      public Builder addAllParams(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureParamsIsMutable();
        super.addAll(values, params_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes params = 4;</code>
       *
       * <pre>
       * 响应参数
       * </pre>
       */
      public Builder clearParams() {
        params_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RspPacket)
    }

    static {
      defaultInstance = new RspPacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RspPacket)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqPacket_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RspPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RspPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014packet.proto\"\\\n\tReqPacket\022\013\n\003udi\030\001 \002(\t" +
      "\022\016\n\006action\030\002 \003(\t\022\016\n\006params\030\003 \003(\014\022\021\n\tclie" +
      "ntVer\030\004 \001(\t\022\017\n\007channel\030\005 \001(\t\"L\n\tRspPacke" +
      "t\022\017\n\007rescode\030\001 \002(\005\022\016\n\006resmsg\030\002 \002(\t\022\016\n\006ac" +
      "tion\030\003 \003(\t\022\016\n\006params\030\004 \003(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ReqPacket_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ReqPacket_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ReqPacket_descriptor,
              new java.lang.String[] { "Udi", "Action", "Params", "ClientVer", "Channel", });
          internal_static_RspPacket_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RspPacket_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RspPacket_descriptor,
              new java.lang.String[] { "Rescode", "Resmsg", "Action", "Params", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
